CREATE TABLE IF NOT EXISTS answers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student TEXT NOT NULL,
  term TEXT NOT NULL,
  direction TEXT NOT NULL,
  correct INTEGER NOT NULL,
  ts REAL NOT NULL
);
