name = "zensho-quiz"
main = "src/index.js"
compatibility_date = "2025-09-01"

[assets]
directory = "./static"
binding = "ASSETS"

[vars]
GOOGLE_CLIENT_ID = ""

[[d1_databases]]
binding = "DB"
database_name = "zensho-quiz-db"
database_id = "f983dd14-0729-434b-adba-cdcb9e5420a9"
